### ISSUE TITLE
[Annotation] Annotating TextClassificationRecords sets the event_timestamp to None 

### ISSUE THREAD

**Issue by dcfidalgo** [recognai/rubrix#1008]
When annotating text classification records via the web app, the event_timestap is lost.
```python
rec = rb.TextClassificationRecord(inputs="test", prediction=[("a", 0.5), ("b", 0.5)], event_timestamp=datetime.now())
rb.log(rec, "test_event_timestamp")
rb.load("test_event_timestamp")   # event_timestamp is fine
# annotate the record in the web app
rb.load("test_event_timestamp")   # event_timestamp is None
```

**Comment by dcfidalgo** [comment]
@frascuchon

**Comment by frascuchon** [comment]
The problem here is that app is not sending the whole record. So missing fields override stored ones.

See response:
<img width="723" alt="Screenshot 2022-01-24 at 15 17 59" src="https://user-images.githubusercontent.com/2518789/150800249-7d44758c-e0a4-4f77-b6d6-f035fd3abd33.png">

and request:
<img width="951" alt="Screenshot 2022-01-24 at 15 18 20" src="https://user-images.githubusercontent.com/2518789/150800285-310b0f4d-bdf9-474d-a77f-230e9596fae9.png">


@leiyre could you please review this issue and change the app api integration for annotation? thanks
