### ISSUE TITLE
rb.init time out, replace httpx with requests, it worked

### ISSUE THREAD

**Issue by HuipengXu** [recognai/rubrix#1207]
as above
![image](https://user-images.githubusercontent.com/23466003/155954822-ea523fd5-6f53-400e-8177-25f9239e782f.png)
![image](https://user-images.githubusercontent.com/23466003/155954841-d93aafc3-83b5-4a8c-9988-b652fa818202.png)
![image](https://user-images.githubusercontent.com/23466003/155954876-8ec7749b-bf9e-44f6-8946-52436f8b8017.png)

**Comment by frascuchon** [comment]
Hello @HuipengXu 

Thanks for reaching out. Could you share a bit more of information about your running environment?

**Comment by HuipengXu** [comment]
rubrix[server]==0.11.0, elasticsearch-oss:7.10.2, 
browser: chrome
server os: centos7
client os: win10
@frascuchon thx

**Comment by frascuchon** [comment]
Okay, If I understood, your problem is that you get a timeout error by requesting with `httpx` but with `requests` everything go fine. It's okay?

I imagine it's working the default timeout behaviour for requests library is to hang until server send the response. What timeout are you setting up? I realized that you have a low connection between server and client, it's not?

**Comment by HuipengXu** [comment]
> Okay, If I understood, your problem is that you get a timeout error by requesting with `httpx` but with `requests` everything go fine. It's okay?

right

> I imagine it's working the default timeout behaviour for requests library is to hang until server send the response. What timeout are you setting up? I realized that you have a low connection between server and client, it's not?

I have try to set timeout 200 seconds, but it not worked

**Comment by dvsrepo** [comment]
Hi @HuipengXu, did you manage to get this work? 

cc @frascuchon

**Comment by HuipengXu** [comment]
@dvsrepo yes
