### ISSUE TITLE
Is text2text supported?

### ISSUE THREAD

**Issue by sam-writer** [recognai/rubrix#1240]
**Describe the bug**

Based on [this page](https://rubrix.readthedocs.io/en/stable/getting_started/supported_tasks.html#tasks-on-the-roadmaphttps://rubrix.readthedocs.io/en/stable/getting_started/supported_tasks.html#tasks-on-the-roadmap), I think Text2Text is not yet supported, but based on [this discussion](https://github.com/recognai/rubrix/discussions/174), it seems like it is. I think this should be more clear.

**To Reproduce**
Documentation bug, no steps beyond visiting the links and reading.

**Expected behavior**
As a potential user evaluating annotation tools for my team, I expect a clear answer about which tasks are supported, and for unsupported tasks, what the roadmap / timeline looks like.

**Screenshots**

<img width="751" alt="image" src="https://user-images.githubusercontent.com/47401552/157505479-b8d475e2-c5c3-432f-b577-dee7b0cd31fe.png">

<img width="919" alt="image" src="https://user-images.githubusercontent.com/47401552/157505551-d39b369c-e0ce-4b03-beb0-e925444aa176.png">

**Environment (please complete the following information):**
 N/A

**Additional context**
Just found out about the project, and am very excited about it, and would like to know if it is currently usable for my team, or something to just keep an eye on.

**Comment by dvsrepo** [comment]
Hi @sam-writer , thanks so much for pointing this out. 

Text2text is indeed supported, currently flagged as experimental because we're looking for feedback:

https://rubrix.readthedocs.io/en/stable/guides/task_examples.html#Text2Text-(Experimental)

@dcfidalgo will fix this documentation issue, and we are planning to open a public roadmap on GitHub soon.

The best way to get a sense of currently supported tasks is here: https://rubrix.readthedocs.io/en/stable/guides/task_examples.html

Please don't hesitate to write us with other questions or suggestions. There's also a Slack channel in case you'd like a more direct interaction.
