### ISSUE TITLE
[Metrics] Symbols count as UPPER tokens or characters for token/entity capitalness metrics

### ISSUE THREAD

**Issue by leireropl** [recognai/rubrix#1244]
When using the **token capitalness** or the **entity capitalness** metrics for analyzing the capitalness on datasets, annotations, and/or predictions, symbols (*, [, (, )...) are counted as **UPPER** results (in other words, as if they were in uppercases). However, Python does not count symbols as uppercase tokens/characters, but the opposite.

**Steps to reproduce the behavior:**
1. Run some of these metrics (i.e. **from rubrix.metrics.token_classification import token_capitalness**), and the same for **token_frequency**. The most frequent results, which are probably symbols, are counted as uppercase tokens.
2. run "(".isupper( ). The result is **FALSE**.

**Expected behavior**
These tokens and entities should be counted as lowercase ones. 

**Additional context**
This problem has been encountered on med7 models.

**Comment by dcfidalgo** [comment]
@frascuchon Is this information returned by Elasticsearch? I tried to figure it out in the source code but got lost ... Actually in python `"*".islower()` and `"*".isupper()` both return False. Thinking about it, these symbols should not be included in the distribution since there is no lower/upper case for those.
