### ISSUE TITLE
Update Docs

### ISSUE THREAD

**Issue by Amelie-V** [recognai/rubrix#1465]

**Comment by Amelie-V** [comment]
https://rubrix.readthedocs.io/en/master/reference/webapp/explore_records.html

Update content + SS in Explore / Token classification:
- [x] Continue text: "In this task predictions and annotation are given as highlights in the input text. Work in progress … >we should explain the highlight for annotation, underline with solid line for prediction and the behavior when filter score is applied (=no solid line)

https://rubrix.readthedocs.io/en/master/reference/webapp/view_dataset_metrics.html
https://rubrix.readthedocs.io/en/master/reference/webapp/dataset.html#metrics

Update content + SS in How to use metrics
- [x] Change text: explain that Metrics are different for "define rules" mode
- [x] Add screenshot of Progress/Stats in explore/annotation in text classifier
- [x] Add screenshot of Progress/Stats in explore/annotation and rules in NER

**Comment by dcfidalgo** [comment]
- [x] https://rubrix.readthedocs.io/en/master/reference/webapp/define_rules.html
- [x] https://github.com/recognai/rubrix / https://rubrix.readthedocs.io/en/master/tutorials/weak-supervision-with-rubrix.html  / https://rubrix.readthedocs.io/en/master/index.html (video)

Optional (SS + videos), I say optional because the non transparent 1px line in TokenClass is missing or the metrics sidebar does not occupy all the vertical space:
- [ ] https://rubrix.readthedocs.io/en/master/tutorials/07-zeroshot_ner.html
- [ ] https://rubrix.readthedocs.io/en/master/tutorials/02-spacy.html
- [ ] https://rubrix.readthedocs.io/en/master/tutorials/05-active_learning.html
- [ ] https://rubrix.readthedocs.io/en/master/tutorials/08-error_analysis_using_loss.html
- [ ] https://rubrix.readthedocs.io/en/master/tutorials/skweak.html
- [ ] https://rubrix.readthedocs.io/en/master/tutorials/weak-supervision-multi-label.html


General improvements:
- [x] https://rubrix.readthedocs.io/en/master/reference/webapp/filter_records.html
