### ISSUE TITLE
[Feature request] Copy text option

### ISSUE THREAD

**Issue by Ankush-Chander** [recognai/rubrix#1616]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to copy record text but I am not able to. Sometimes I want to copy text and check out it"s dependency parser on another tool but currently there is no straightforward way to do so.

**Describe the solution you'd like**
A copy option in the ":" next to "View Metadata" would be great.

**Describe alternatives you've considered**
1. Alternative can be a copy icon next to ":" but that won"t be neat as copy is a peripheral activity
2. Inspect result item and copy text from developer tools. (Overkill)

**Comment by dcfidalgo** [comment]
Hi @Ankush-Chander and thanks a lot for your feedback! To be sure, you are referring to the record texts for token classification datasets in the UI, is that right?

CC @leiyre @Amelie-V

**Comment by Ankush-Chander** [comment]
Hi @dcfidalgo 

That's right. 
But it will be useful for other tasks dataset also.

**Comment by Amelie-V** [comment]
### Spec

All tasks, All mode

### Add a new option to the overflow menu (three dots icon)

- New option: "Copy text" (correspond to the input text)
- Change Discard to "Discard record"
- In order of: "View metadata", "Copy text", "Discard record"

### Discard record State

-  Always maintain Discard copy (instead of Discarded)
-  Apply disabled state when Discard record is activated
