### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by leandroroser** [recognai/rubrix#1731]
Hi,

I'm using Rubix in my current pipelines and feels amazing. I'm wondering if the app is planning to support entity linking type of annotations? Thanks.

**Comment by davidberenstein1957** [comment]
@leandroroser sorry for the late reply, I think we missed this during our rebranding. For now, we are not focussing on entity-linking, but it is good to know that there is demand for this feature, so we will keep it in mind. Especially, since we will be re-evaluating our roadmap during the coming weeks. If you have any other questions or implementation issues. Feel free to contact me via e-mail or slack:)

**Comment by leandroroser** [comment]
Thanks @davidberenstein1957 !
