### ISSUE TITLE
Similarity search with vectors

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#1757]
In order to enable similarity and vector search features (bulk labeling, similarity-based data curation, etc.) the first step is to enable the ability to store a vector associated with a record.

The main idea is to enable users to embed a record (using their embedding method of choice) and then add the vector as a field associated with the record. In this way, it can already be used with ES/Opensearch for KNN as well as for other use cases.

There are some things to take into account:

- Compat between Opensearch and Elasticsearch
- Work needs to be done at the Server and the Client level

We already started working on this: https://github.com/recognai/rubrix/pull/214 but stopped because Elasticsearch's support was limited at the time.

There are several discussions around this topic:
https://github.com/recognai/rubrix/discussions/177
https://github.com/recognai/rubrix/discussions/1079

## Tasks
- [x] #2026
- [x] #2027 
- [x] #2028 
- [x] #2029

**Comment by ufukhurriyetoglu** [comment]
there is an already declined PR relevant to this issue, should I open a new branch ? apart from that I was not know Amazon Opensearch, I will check it to see how we can support both of ES / Opensearch.

**Comment by dvsrepo** [comment]
I think you can open a  new branch but feel free to take the code from that PR if useful

**Comment by ufukhurriyetoglu** [comment]
opened a new branch by targeting the releases/1.x

**Comment by mnschmit** [comment]
Hi all,

I was talking to @davidberenstein1957 yesterday. I mentioned that I was working on a custom data import pipeline that filters (fuzzy) document duplicates and ultimately logs into Argilla. He told me about your plans to implement a semantic search feature and he asked me to share my use case here:

The stream of text data I am working with in production often contains near-duplicates (this can be the same text, e.g., a letter, where only the name is swapped; or different versions/drafts of the same text etc.). Since I do not want to waste time hand-labeling very similar texts, I filter them out using tf-idf features. I suppose that dense embeddings could also work but actually I really only want to find very, very similar texts. Hence, I chose tf-idf.
My workflow is 1. update tf-idf features of the "old", already logged texts with the new candidate texts 2. filter the "new" texts by keeping only one representative of a cluster in case of very high similarity scores among only the new ones 3. assign each remaining new text the highest similarity I can find to any existing "old" text 4. only log those new texts that are dissimilar enough to Argilla.

At the moment, I simply store the tf-idf features in an S3 bucket and update them after data import but it would be great to have support for such a filtering directly from Argilla itself if that is compatible with what you're planning:
- Either a feature that stores similarity to existing records as meta data when the record is first logged.
- Or simply an integrated similarity computation given a record before logging and an exported dataset. (and then let the user decide manually whether to log it or not or what to store - like I'm doing right now)
- simply storing an embedding (vector) together with a record might be useful if you use a fixed embedding model and it would save the user the trouble of having a separate feature store (like I'm having right now). For my more literal tf-idf features that have to be updated with new incoming documents, I don't see how it would help my use case to simply have the possibility of storing a fixed vector together with a record.

I hope that helps and keep up the good work :)

**Comment by frascuchon** [comment]
Refs #1917

**Comment by ufukhurriyetoglu** [comment]
nice use case and impressive solution @mnschmit thanks for sharing! the design notes also very helpful 👍

**Comment by dhruvsakalley** [comment]
I'm not sure if this helps, but if you want to vectorize the query and the documents with the same encoder, that requires a live encoder API. If you do not want a live encoder especially when using dense embeddings for the documents, you could use simpler encoders (such as the native elasticsearch BM25) for the initial seed document set and expand on the semantic aspects using the precomputed embeddings of the seed embedding. While this would not capture the query semantics well, it still does a decent job expanding on result semantics. Additionally, one could use Maximum Marginal Relevance (MMR) to introduce a post reranking, thereby maximizing novelty in the result set. It would be interesting if someone compared the resultset returned with this approach using something like Area Under the Margin (AUM) , from a prior model iteration to see if the results we get are indeed useful to label. 

Explainations
- http://www.cs.cmu.edu/~jgc/publication/The_Use_MMR_Diversity_Based_LTMIR_1998.pdf 
- https://deepai.org/publication/identifying-mislabeled-data-using-the-area-under-the-margin-ranking#:~:text=Area%20Under%20the%20Margin%20%28AUM%29%2C%20which%20is%20the,AUM%20differs%20significantly%20between%20correctly-%20and%20mislabeled%20examples.

**Comment by dvsrepo** [comment]
> I'm not sure if this helps, but if you want to vectorize the query and the documents with the same encoder, that requires a live encoder API. If you do not want a live encoder especially when using dense embeddings for the documents, you could use simpler encoders (such as the native elasticsearch BM25) for the initial seed document set and expand on the semantic aspects using the precomputed embeddings of the seed embedding. While this would not capture the query semantics well, it still does a decent job expanding on result semantics. Additionally, one could use Maximum Marginal Relevance (MMR) to introduce a post reranking, thereby maximizing novelty in the result set. It would be interesting if someone compared the resultset returned with this approach using something like Area Under the Margin (AUM) , from a prior model iteration to see if the results we get are indeed useful to label.
> 
> Explainations
> 
>     * http://www.cs.cmu.edu/~jgc/publication/The_Use_MMR_Diversity_Based_LTMIR_1998.pdf
> 
>     * https://deepai.org/publication/identifying-mislabeled-data-using-the-area-under-the-margin-ranking#:~:text=Area%20Under%20the%20Margin%20%28AUM%29%2C%20which%20is%20the,AUM%20differs%20significantly%20between%20correctly-%20and%20mislabeled%20examples.

Hi, @dhruvsakalley thanks so much for the inputs! For this very first (limited) release, we'll just support `knn` of similar records: given a record in the record list, you'll be able to find the most similar records based on the stored vectors (which can be anything generated by an encoder and that they are logged together with the record info at ingestion time). Then we are planning to provide pluggable embedding services which can encode records during ingestion/indexing time and which can be used for encoding queries too (the latest cross-lingual model from Cohere seems very powerful for this).

We have been discussing of leveraging the internal vectors of elasticsearch too, because as you said they might be enough for certain use cases (example deduplication or label error detection), so thanks a lot for the suggested readings which I didn't know. We'll take a look and hopefully continue the conversation with you!
