### ISSUE TITLE
Button enity-label gets covered by show less button 

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#1779]
**Describe the bug**
With a lot labels the button gets covered.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a TokenClassification dataset
2. Click on show more labels
3. See error

**Expected behavior**
I would expect to start a new-line.

**Screenshots**
![image](https://user-images.githubusercontent.com/25269220/196914449-8a15f585-bb8d-4c31-a999-38b0e775cb7c.png)

**Environment (please complete the following information):**
 - OS [e.g. iOS]: Mac
 - Browser [e.g. chrome, safari]: Firefox
 - Rubrix Version [e.g. 0.10.0]: 1.x
 - ElasticSearch Version [e.g. 7.10.2]: N.A.
 - Docker Image (optional) [e.g. rubrix:v0.10.0]: N.A.

**Additional context**
N.A.

**Comment by Amelie-V** [comment]
@leiyre 

Since the buttons refactorization, we lost the transparency on that button. 
We have at least 2 options:
- Redo the transparency to enable read the label. (creating an exception on one button..not 100% satisfactory)
- Start a new line. (This option will increase the high of the label caption component).
- new 💡

**Comment by Amelie-V** [comment]
After discussion with @leiyre , let's put it and the queue of the label list
