### ISSUE TITLE
Predicted field should be defined as a range (accuracy for example)

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#1833]
**Is your feature request related to a problem? Please describe.**
For multi label text classification, predicted records filter is quite strict, and is not really useful. 
 
**Describe the solution you'd like**
A better way of filter, show records accuracy could be define the `predicted` record value (ok, ko actually) as a number between 0 and 1, describing how near the prediction is respect annotation. 

This could generalize the text classification problem (not only for multi-label) 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by dcfidalgo** [comment]
:+1: For multi-label text classification, the predicted ok/ko filter is not really useful. I like the idea of having a score that somehow reflects the "correctness" of a prediction. Maybe a simple approach would be to count incorrect/missing predictions (`incorrect`) and correct predictions (`correct`) and do:
```python
correct/(incorrect+correct)
```

By the way, is there a reason why we don't include the `Score` filter in multi-label? 

Another thing, because I just checked this filter in a single-label classification dataset: when there are few predictions, the new visualization of the scores is a bit hard to see, see the screenshot below:
![Screenshot from 2022-02-17 10-03-49](https://user-images.githubusercontent.com/15979778/154442692-f1b59249-1ec5-4b8d-89b4-3041dc7e30cf.png)

**Comment by frascuchon** [comment]
Now, we can play with scores also for token classification. I would like to tackle this issue since can be interesting to allow filtering by score in multi_label text classification datasets

**Comment by dvsrepo** [comment]
@frascuchon here we are talking about two different things as far as I understand:

1. `scores` for multilabel (and token classification I guess)
2. `predicted` as a range (between 0-100 or 0-1) instead of ok vs ko

What should we do?

**Comment by frascuchon** [comment]
We will tackle the `predicted` range but not the scores for now.
