### ISSUE TITLE
Allow to launch the argilla server in a  different `base_url` 

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#1914]
**Is your feature request related to a problem? Please describe.**
Some server integrations are using proxies to forward the argilla server UI under a subpath, but for those cases, the integration is not working. (See #1899)

**Describe the solution you'd like**
We need to improve the way the application UI is served in addition to allowing the setting of the FastAPI base URL parameter.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by frascuchon** [comment]
I would like to plan this issue for the next release. This feature is a blocker for some interesting integrations like Orchest. 

Could we have a call about this next week @dvsrepo @leiyre @keithCuniah @davidberenstein1957?

**Comment by frascuchon** [comment]
Refs #1899

**Comment by frascuchon** [comment]
Ideally, from the client, we should include a new command line script to launch Argilla server, but keep the module fashion call:

```bash
argilla start|run|serve --base-url /argilla
```

**Comment by davidberenstein1957** [comment]
@frascuchon I have some time during the coming days. Maybe we can discuss this during/after the 1.2.0 planning. Also, I asked Esraa Madi to provide some input on her usecase.

**Comment by frascuchon** [comment]
@dvsrepo do you have any insight to share about this?

**Comment by dvsrepo** [comment]
No insights on my side, I like the client idea and would only make sure it's a good solution for services like Orchest

**Comment by dhruvsakalley** [comment]
I am working with IIS reverse proxy and running into a similar need, this might probably help me.

**Comment by EsraaMadi** [comment]
> @frascuchon I have some time during the coming days. Maybe we can discuss this during/after the 1.2.0 planning. Also, I asked Esraa Madi to provide some input on her usecase.



> Ideally, from the client, we should include a new command line script to launch Argilla server, but keep the module fashion call:
> 
> ```shell
> argilla start|run|serve --base-url /argilla
> ```

Sorry I did not get where I should this line in the client like Orchest?

**Comment by dvsrepo** [comment]
> I am working with IIS reverse proxy and running into a similar need, this might probably help me.

@dhruvsakalley this is finally here in `1.2.0` which we released yesterday: https://docs.argilla.io/en/latest/getting_started/installation/server_configuration.html#using-a-proxy Please let us know if this works for your setup!

**Comment by samhardyhey** [comment]
Hey everyone, having a bit of trouble getting this to work with Traeifk. I've been following the [documentation](https://docs.argilla.io/en/latest/getting_started/installation/configurations/server_configuration.html#using-a-proxy), specifically including `ARGILLA_BASE_URL` within the argilla server compose service. This variable is propagating, is present within the running container, and search/replaces through the nuxt static bundle just fine (verified within server container). My compose/traefik config looks like this:

```version: "3.9"

x-service-traefik-web:
  &service-traefik-web
  labels:
    - "traefik.enable=true"
    - "traefik.docker.network=dev_service_loadbalance"
    - "traefik.port=6900"
    - "traefik.backend.loadbalancer.stickiness=false"
    - "traefik.weight=1"
    - "traefik.frontend.passHostHeader=true"
    - "traefik.frontend.headers.SSLProxyHeaders=X-Forwarded-Proto:https"
    - "traefik.frontend.rule=PathPrefix:/argilla/, /argilla"
    - "traefik.frontend.redirect.regex=^(.*)/argilla/$$"
    - "traefik.frontend.redirect.replacement=$$1/argilla/"

services:
  argilla:
    image: argilla/argilla-server:latest
    environment:
      ARGILLA_ELASTICSEARCH: http://elasticsearch:9200
      ARGILLA_ENABLE_TELEMETRY: 0
      ARGILLA_LOCAL_AUTH_USERS_DB_FILE: /config/.users.yaml
      ARGILLA_BASE_URL: /argilla
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 30s
      update_config:
        delay: 2s
      <<: *service-traefik-web
    networks:
      - frontend
      - backend

  elasticsearch:
    image: elasticsearch:8.5.3
    environment:
      - node.name=elasticsearch
      - cluster.name=es-argilla-local
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.routing.allocation.disk.threshold_enabled=false
      - xpack.security.enabled=false
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - backend
  kibana:
    image: kibana:8.5.3
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 0
    networks:
      - backend

networks:
  backend:
    name: argilla_backend
  frontend:
    external: true
    name: dev_service_loadbalance
```

Where we use traefik as a load balancer and for service discovery across a broader docker swarm configuration. We have well-established patterns for this. When I hit service, I'm met with a loading wheel that never resolves:

![argilla_debug](https://github.com/argilla-io/argilla/assets/18030446/7ac3d11b-3657-4c65-8706-b7ed6a7287a0)

Pretty sure my Traefik config/networking is fine because I'm getting at least the partial static bundle through, but perhaps there are other places in the front-end where the `ARGILLA_BASE_URL` is meant to search/replace but hasn't?

I've A/B'd this compose with/without formally deploying with traefik and I've noticed that with the traefik deployment, I'm missing some additional JS files within the browser waterfall. 

Probably user error, any help very much appreciated!
