### ISSUE TITLE
[Similarity search] Add documentation guides

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#2027]

**Comment by davidberenstein1957** [comment]
Thanks, I will take a look at this next week.

**Comment by dvsrepo** [comment]
@davidberenstein1957 I'll take this one and request advice and reviews from you

**Comment by davidberenstein1957** [comment]
Also, provide text for the helper button within the UI

**Comment by Amelie-V** [comment]
Helper modal:
Max 600 caracteres, title included

**Comment by dvsrepo** [comment]
@leiyre this is the text to be included in the helper modal:

# Similarity search

Since `1.2.0` Argilla supports adding vectors to Argilla records which can then be used for finding the most similar records to a given one. 

This feature uses vector or semantic search combined with more traditional search (keyword and filter based). Vector search leverages machine learning to capture rich semantic features by embedding items (text, video, images, etc.) into a vector space, which can be then used to find "semantically" similar items.

To benefit from this feature, your data team must include vectors associated with each record when they create the dataset. 

To learn more about this feature you can visit the [documentation page](https://docs.argilla.io/en/latest/guides/features/semantic-search.html)

**Comment by dvsrepo** [comment]
Pending thing to close this issue:

- [ ] @leiyre and @Amelie-V send some screenshots to @dvsrepo to add them to the reference for Argilla UI once we have something. You can use the datasets from dev

**Comment by Amelie-V** [comment]
@leiyre Please remove the last sentence from the help. "To learn more about this feature you can visit the [documentation page](https://docs.argilla.io/en/latest/guides/features/semantic-search.html)" 
We already have the CTA linked to the doc and the destination is the same.

**Comment by dvsrepo** [comment]
@Amelie-V if you can send me one or two screenshots I can include them in the docs and close the first version of the full doc changes. It can be a general screenshot to at least show the overall feat or several screenshots with a user flow

**Comment by dvsrepo** [comment]
@frascuchon let's leave this one as the main doc issue. As mentioned before, I won't do more work on the docs
