### ISSUE TITLE
Specify and describe text limit that may affect the defined backend limits

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#2272]
**Is your feature request related to a problem? Please describe.**
When logging large input data, or with huge complex metadata info, the process fails due to a backend error.

**Describe the solution you'd like**
We should prevent this situation and provide users a limit + early validation to avoid a backend error.

**Describe alternatives you've considered**
N/A

**Additional context**
Refs: #2261

**Comment by davidberenstein1957** [comment]
@frascuchon would it be possible to create an in-server temporary storage/queue-ing mechanics of un-processed data so that the server processing is not blocking data uploads if we were to move record validations to the client side? I was just looking at uploading data and size/processing limitations are rather blocking in my case, and this has also been a recurring issue for several other users. 

![image](https://user-images.githubusercontent.com/25269220/218802058-32d392d0-da81-415b-8a84-18c7f8ce5394.png)

**Comment by davidberenstein1957** [comment]
I really love this from Ray

https://docs.ray.io/en/latest/ray-core/ray-dashboard.html
