### ISSUE TITLE
`sort`functionality for loading data with the Python API

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#2433]
**Is your feature request related to a problem? Please describe.**
I need to have the most recent 100 entries sorted on the last updated DateTime without getting all data.

**Describe the solution you'd like**
I would like to have `rg.load("name", limit=100, sort=[("field", "asc|desc")])`

**Describe alternatives you've considered**
N.A.

**Additional context**
looking at the UI payload for sort, this should be possible

**Comment by davidberenstein1957** [comment]
@frascuchon I think the sort should default to `event_timestamp` by default from the serverside. I feel that having added new records, I would always expect to see them at the top of the page/dataset as confirmation. 

I also added an initial [test](https://github.com/argilla-io/argilla/blob/7b9e5adf274fb85375975bff1c9ea88436662b92/tests/client/test_api.py#L578).

**Comment by frascuchon** [comment]
I've been taking a look into the implementation details. We must tackle this carefully since changes would be a bit more difficult. 
We're using a more performance pagination for elasticsearch (see [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html)), but it depends on how sorting is setup. 
We will include this info in the `next_idx` field to apply to sort as expected. I will create a separate PR to add sorting to this endpoint.
