### ISSUE TITLE
Unresponsive hyperlink to access Argilla dashboard in argilla v1.4.0

### ISSUE THREAD

**Issue by anammari** [recognai/rubrix#2527]
**Bug description:**
Just reporting an issue with the hyperlink that is generated in Jupyter notebooks to access the Argilla dashboard when writing a new Argilla dataset. The hyperlink does not work with me in the new Argilla version v1.4.0 (it doesn't respond to user clicks) but is working fine in the older version (v.1.3.0).

**To Reproduce:**
1. pip install argilla==1.4.0 
2. Open Jupyter notebook and add code to write an Argilla dataset to the dashboard.

Example:
```

import argilla as rg

# get the label strings to turn int ids into string names
labels = banking_ds["test"].features["label"].names

records = []
for example in test_ds_with_preds:
    # create a record with ground-truth annotations and gpt-3 predictions
    record = rg.TextClassificationRecord(
        inputs={"text": example["text"], "explanation": example["explanation"]},
        annotation=labels[example["label"]],
        prediction=[(example["prediction"].lower(), 1.0)]
    )
    records.append(record)

# create a dataset in Argilla
rg.log(records, "banking_sentiment_zs_gpt3")

```

3. Execute the code cell in Jupyter.
4. The generated hyperlink in the output to access the Argilla dashboard does not respond to user clicks. 

**Expected behavior:**
The generated hyperlink in the output to access the Argilla dashboard should open a new browser tab with the Argilla dashboard. 

**Screenshots:**
![image](https://user-images.githubusercontent.com/2264734/224895801-bd6d0a1a-4359-4c85-a7a3-22ea35a11921.png)

**Environment:**
 - OS: Linux
 - Browser: Chrome, Edge
 - Argilla Version: v1.4.0:
 - Docker Images: 
 1. Jupyter: https://huggingface.co/spaces/aammari/jupyter-stacks-voila/blob/main/Dockerfile
 2. Argilla: https://huggingface.co/spaces/aammari/ndis-nlp-data-validation/blob/main/Dockerfile

**Comment by tomaarsen** [comment]
@anammari I appreciate your detailed report!

This is caused by #2350, i.e. the move to use `rich` its `print` method rather than the default `print`. Why exactly the `rich` printed URLs are not clickable: I'm not sure. I suspect that Jupyter notebooks override the default `print` behaviour to include the opportunity to click the link. I can't find an issue for this on the [rich repo](https://github.com/Textualize/rich/issues?q=jupyter) I'm afraid.

We only use the `rich` `print` in exactly one place in the codebase: 
https://github.com/argilla-io/argilla/blob/5ff0a480993fc9e594dc097ea25cf846d9123016/src/argilla/client/client.py#L422

A potential solution is to rely on the default `print` if we detect that users are using a Jupyter Notebook environment, as that one is already sufficient in that environment, and only use the `rich` `print` in the terminal. 
I'm open to hear your thoughts.

cc: @frascuchon

**Comment by frascuchon** [comment]
Okay. These lines are working from a jupyter notebook:

```python
from rich import print
print("Visit my [link=https://www.willmcgugan.com]blog[/link]!")
```

We should adapt our link message to [this](https://rich.readthedocs.io/en/stable/markup.html#links) format

**Comment by tomaarsen** [comment]
Very smart. I can make that happen first thing in the morning tomorrow if you'd like.
