### ISSUE TITLE
Show only records where annotations!=predictions

### ISSUE THREAD

**Issue by cceyda** [recognai/rubrix#2553]
**Is your feature request related to a problem? Please describe.**
I'm logging the eval set predictions to argilla so that someone(sometimes me) can manually inspect the error cases the model makes. It would be nice if there was a way to search/filter only records where there is a mismatch. And possibly allow filtering with smarter criteria (like score, where only certain labels are mismatched etc)

**Describe the solution you'd like**
The coolest solution would be if we can show a confusion matrix 💡 
and I can click on a value(or values) and it would only show me the records that belong to that error class 🤯 

**Describe alternatives you've considered**
I can compare annotations & predictions and add a metafield indicator.

**Additional context**
Pretty please this would be so useful for token classification.

**Comment by cceyda** [comment]
Could be implemented along with this feature: https://github.com/argilla-io/argilla/issues/2056
In the back end can add an id to each value of the confusion matrix like "cm_row_col" then use that to filter the records using the existing search mechanism

**Comment by dvsrepo** [comment]
Hi @cceyda prior to Rubrix and Argilla, we used to have a confusion matrix in the UI, we'll certainly look into this at some point in time. In the meantime, we compute a filter under the predictions block that lets you filter predictions ok vs ko. It's not ideal for multilabel and token classification because it's binary (all correct or not) but we found it useful for our projects. Let me know if you don't see it because if you have predictions and annotations it should be there, otherwise it's a 🐛
