### ISSUE TITLE
Correct wording in `updated at` field

### ISSUE THREAD

**Issue by nataliaElv** [recognai/rubrix#2772]
**Is your feature request related to a problem? Please describe.**
In the `updated at` field in Home, when something was updated or created hours ago it should say "X hours ago". Same in the `created at` column.
<img width="272" alt="Captura de pantalla 2023-04-24 a las 15 55 49" src="https://user-images.githubusercontent.com/126158523/234018111-0737b37f-33c6-4dae-b1cd-0710b592ae1e.png">

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alvarobartt** [comment]
I guess it has something to do with the timestamp as that's calculated compared to the current timezone where someone is located (usually their default system's time zone), since I checked some other datasets and it's indeed formatted as `N hours ago` in some cases, so the issue could be in the timestamp used.

<img width="211" alt="image" src="https://user-images.githubusercontent.com/36760800/234271865-0b603b33-4857-41c8-ab67-d69dce88ead6.png">
