### ISSUE TITLE
Remove the record counts from pagination

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#2917]
- Frontend: remove the record count (1 of ...) 
- Frontend: Hide from pagination (OK)
- Backend: stop computing the total number of records when fetching records.

**Comment by alvarobartt** [comment]
Hi @frascuchon does it mean that the API will no longer return `{"items": [{...}, ...], "total": ...}`? If so I would need to change some things too, since I'm using the `total` value of the first request to compute the `batch_size` when retrieving the pushed records from Argilla.

**Comment by frascuchon** [comment]
I see @alvarobartt. Could we show a progress other than a progress bar to avoid computing the total number of expected records?

**Comment by alvarobartt** [comment]
I mean there's no way to actually add any progress tracker if we don't know the amount of records/batches that we need to fetch, so maybe we can just rely on something like `Fetching records from Argilla...`, but without any progress bar/tracker.

**Comment by alvarobartt** [comment]
Also maybe we can get that from the metrics when computed? cc @frascuchon to call that endpoint once, and then use the value we get from there in combination with the offset and limit API params?

**Comment by frascuchon** [comment]
Yes! The metrics can be an option to fetch total info. But once we'll introduce queries, this approach may change.

**Comment by keithCuniah** [comment]
**Comment regarding ajustement todo in front end part,** 

We need to be carefull when refactoring the existing code.

**List of impacts by components/model :**
1/ FeedbackPagination.component.vue : 
- the total_records is used to compute the number of total page 
- it's also used to render the pagination component (if no total_records, the component is not rendered)

2/ CenterFeedbackTask.content.vue :
- when total_records change, we reinitiate the flag areResponsesUntouched to true (this help us to show are not a toast on change route or on change filter) 
- also used to know in which page the user is in order to allow to go to next record or not on submit/discard

3/ RecordFeedbackTaskAndQuestionnaire.content.vue :  
- it's where the total_records is fetch and insert in the orm
- it's used as a flag to show or not a message in case there is no record

4/ FeedbackTask.model.js && feedbackTask.queries.js : 
where there is the attribute total_record && queries to update/get the value from the orm

=> **When the total record will be removed from the api, we have to clean the front orm and adapt the 3 components to get the toal record from the metrics instead of the previous way**
