### ISSUE TITLE
[DOCS] datamodel.html links not working

### ISSUE THREAD

**Issue by peppinob-ol** [recognai/rubrix#3411]
## Which page or section is this issue related to?
https://docs.argilla.io/en/latest/reference/datamodel.html

All the following link are **not working**:
[build datasets](https://docs.argilla.io/en/latest/reference/datamodel.html#../guides/features/datasets.ipynb)
[log](https://docs.argilla.io/en/latest/reference/datamodel.html#rb-log)
[dive into your dataset](https://docs.argilla.io/en/latest/reference/datamodel.html#../reference/webapp/dataset.md)
[load](https://docs.argilla.io/en/latest/reference/datamodel.html#rb-load)
[prepare it for training](https://docs.argilla.io/en/latest/reference/datamodel.html#../guides/features/datasets.ipynb#prepare-dataset-for-training)
[this guide](https://docs.argilla.io/en/latest/reference/datamodel.html#../guides/llms/practical_guides/create_dataset.ipynb)

```[tasklist]
### Tasks
```

**Comment by tomaarsen** [comment]
I've tried to chase down the documents that these links should be pointing to, but I'm unable to find them. They seem to have been deleted for months now, even since *before* the large documentation refactor of #2948.
@davidberenstein1957 you might know what these files should be, and otherwise what the fate of this bit of documentation should be.

- Tom Aarsen

**Comment by davidberenstein1957** [comment]
Hi @tomaarsen @peppinob-ol, this seems to have been resolved so I'm closing this issue.
