### ISSUE TITLE
[BUG] `dict` values for `LabelQuestion` are not represented in `datasets` card

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#3614]
**Describe the bug**
I created a dataset with `{"1": "value-2", "2": "value-2"}` but there is no way of retrieving the `values()` from the dicts.

**Expected behavior**
I would expect this to be represented somewhere.

**Environment:**
N.A.

**Additional context**
https://huggingface.co/datasets/argilla/emotion

**Comment by alvarobartt** [comment]
Right, those are not represented as we don't have a clear way to determine whether the `values()` have been automatically fulfilled or introduced by the user, we could add a check whether `text == value` and just don't show those in that scenario, but show those when `text != value`, but is it really useful? As AFAIK that's something that only makes sense in the Argilla UI, since the annotations will come with the `value` not the `text`

**Comment by davidberenstein1957** [comment]
Yes, it mostly makes sense in the Argilla UI but I would still find it weird not to see the entire dataset context. Comparable to a textcat model predicting the IDs instead of the labels based on the `label_2_id`-mapping.

**Comment by alvarobartt** [comment]
Oh ok, so you mean when calling `FeedbackDataset.from_huggingface`, right? Then the information can be reflected in the `argilla.yaml` configuration file we're pushing to the Hub, and later be retrieved via `values()` 👍🏻
