### ISSUE TITLE
[BUG] Invalid value range for `RatingQuestion` not catched during Python SDK validation

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#3624]
**Describe the bug**
Defining a rating question with this range `[0,1,2,3,4,5]` doesn't throw a validation error on the Python SDK instantiation, but then fails when pushing the dataset to Argilla and with an exception that doesn't not provide any indication of what went wrong.

**Stacktrace and Code to create the bug**

```python
dataset = rg.FeedbackDataset(
    fields=[rg.TextField(name="user-message"), rg.TextField(name="assistant-message")],
    questions=[
        rg.TextQuestion(name="response", title="Write a helpful, harmful, accurate response"),
        rg.RatingQuestion(name="question-rating", title="Rate the relevance of the user question", values=[0,1,2,3,4,5], required=False)
    ]
)
```
doesn't throw a validation error, but the following does:

```python
ds = dataset.push_to_argilla(name="argilla_assistant", workspace="admin")
```

```
Exception: Failed while adding the question 'question-rating' to the `FeedbackDataset` in Argilla with exception: 
Argilla server returned an error with http status: 422
Error details: [{'code': 'argilla.api.errors::ValidationError', 'params': {}}]
```
**Expected behavior**
I would expect the Python SDK to throw an easy to understand error message during instantiation, instead of not throwing any error and getting the error from the API with no explanation about the problem.

Related note: Besides catching this specific error on the SDKs side, which I assume is a bug: we should put more effort into providing useful, descriptive error messages on both sides (Python SDK, API)

**Environment:**
 - Argilla Version: 1.14.1
 - ElasticSearch Version [e.g. 7.10.2]:
 - Docker Image (optional): quickstart

**Additional context**

**Comment by alvarobartt** [comment]
Hi @dvsrepo thanks for reporting this issue! Indeed we've always supported any arbitrary number of elements and range of values, but I think that now we just support values within the range [1, 10]. Indeed I think this bug was introduced in https://github.com/argilla-io/argilla/pull/3452, but according to my comment at https://github.com/argilla-io/argilla/pull/3452#discussion_r1274693159, I guess we can now drop the support for any arbitrary range and add a validator instead of just raising the warning 👍🏻

**Comment by davidberenstein1957** [comment]
Hi @alvarobartt IMO this extends to the general usage of Python API vs the server validation. I think it makes sense to validate record creating client-side too. It might be a duplicate check but in terms of developer experience it is generally much easier to debug than the server responses.

**Comment by davidberenstein1957** [comment]
https://github.com/argilla-io/argilla/issues/3223

**Comment by alvarobartt** [comment]
> Hi @alvarobartt IMO this extends to the general usage of Python API vs the server validation. I think it makes sense to validate record creating client-side too. It might be a duplicate check but in terms of developer experience it is generally much easier to debug than the server responses.

Yes, indeed we validate mostly everything in the client side, the only missing validation I think is for the responses, but that's a not so common scenario, since logging manually introduced responses from the Python client is not a common thing. Anyway, I agree we can improve the general validation, please refer to the issue you pointed out to continue the conversation 😄

**Comment by dvsrepo** [comment]
Yes, I think the client-side validation has improved a lot from past
versions, this was more a misalignment of what was a hard validation in the
server vs a soft validation on the SDK side.

My dream would in any case be: to go beyond Pydantic's default validation
messages (on both layers, client and server) and show the users more
meaningful messages.
