### ISSUE TITLE
[FEATURE] ArgillaTrainer - add `push_to_hub` method

### ISSUE THREAD

**Issue by tomaarsen** [recognai/rubrix#3633]
**Is your feature request related to a problem? Please describe.**
Related: https://github.com/argilla-io/argilla/pull/3467#discussion_r1305248272

**Describe the solution you'd like**
Users might want to `push_to_hub` their trained models. 

**Describe alternatives you've considered**
* Use `save` followed by `AutoModel.from_pretrained("...").push_to_hub`

**Additional context**
Should be implemented after #3467

---

- Tom Aarsen

**Comment by vasudevanubrolu** [comment]
Hi @davidberenstein1957 can I pick this up ?

**Comment by davidberenstein1957** [comment]
Files can be found in two places:
- src/argilla/training (old)
- src/argilla/client/feedback/training (new)

The `ArgillaTrainerSkeleton` should get a new `push_to_huggingface` that raises a NotImplementer error.
- src/argilla/training/base.py
- src/argilla/client/feedback/training/base.py

The framework classes defined by `Argilla*Trainer` should get a `push_to_huggingface` which mimics the [Hugging Face implementation](https://huggingface.co/docs/transformers/model_sharing#use-the-pushtohub-function), the [spaCy implementation is a little bit different](https://huggingface.co/docs/hub/spacy#sharing-your-models).
- src/argilla/training/transformers.py
- src/argilla/training/span_marker.py
- src/argilla/training/spacy.py

Also, you will need to define a test for doing this but this might be a bit less intuitive because they should only run if `HF_TOKEN` or `HF_HUB_ACCESS_TOKEN` is present.
- tests/integration/training/test_base.py
- tests/integration/client/test_dataset.py (for inspiration regarding token-available testing)

**Comment by tomaarsen** [comment]
We may want to use `push_to_huggingface` instead of `push_to_hub`, following other methods related to HF that we have.

**Comment by davidberenstein1957** [comment]
@tomaarsen, thanks I changed it.

**Comment by davidberenstein1957** [comment]
@plaguss this align well with your PR in draft https://github.com/argilla-io/argilla/pull/3857

**Comment by plaguss** [comment]
Happy to grab this one as soon as #3857 is ready! (if its still free)
