### ISSUE TITLE
docker-compose up is showing error

### ISSUE THREAD

**Issue by Arvind644** [recognai/rubrix#369]
when I run docker-compose up it shows error

![error](https://user-images.githubusercontent.com/65646063/134007091-22538189-5d99-4fcf-9d85-64a67a37ccbb.png)

**Comment by dcfidalgo** [comment]
Thanks a lot, @Arvind644, for reporting! It seems like docker is not running on your system. Since none of us is working with windows it is a bit difficult for us to reproduce your error, but I attach a couple of links that hopefully point you in the right direction:
- https://stackoverflow.com/questions/64952238/docker-errors-dockerexception-error-while-fetching-server-api-version
- https://docs.docker.com/desktop/windows/install/

Hope I could help! 🙂

**Comment by Arvind644** [comment]
@dcfidalgo I have docker desktop installed with wsl2 ubuntu . I just tried it with windows manager powershell and it works. It didn't worked in vscode terminal

**Comment by dcfidalgo** [comment]
Great to hear that it works now! Have fun with Rubrix! 🙂

**Comment by Arvind644** [comment]
@dcfidalgo Thank you But it is very slow in pulling the image.  Its already 15 mins and not even the half part is done. Does there is way to do that fast.
