### ISSUE TITLE
[FEATURE] align `external_id` usage with user stories

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#3757]
**Is your feature request related to a problem? Please describe.**
`add_records(same_record)` and `add_records(same_record)`  might lead to errors
methods like `delete_records` or `filter_by` record IDs aren't aligned with the different dataset types. Also, records might need to be updated based on `external_id` from another database.

**Describe the solution you'd like**
- by default generating a UUID
- allowing to overwrite existing `external_id`

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by lit-in** [comment]
Whenever new information like user feedback is available, I would like to update the corresponding field of the record.
For example, user feedback is not available at the time of record creation but is immensely helpful for annotators. I have a metadata property to filter records with user feedback, so annotators could prioritise them. 
Tried:
1. [update_records](https://docs.argilla.io/en/latest/practical_guides/create_dataset.html#update-records) API doesn't allow updating a particular record’s fields value
2. add_records API fails due to the UniqueConstraint `record_external_id_dataset_id_uq`
