### ISSUE TITLE
[FEATURE] Notify dataset progress when downloading datasets from huggingface

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#3888]
**Is your feature request related to a problem? Please describe.**
The `FeedbackDataset.from_huggingface` class method does not show the progress once the dataset is downloaded and records are parsed.

```python
import argilla as rg
from datasets import load_dataset

# load an Argilla Feedback Dataset from the Hugging Face Hub
dataset = rg.FeedbackDataset.from_huggingface("argilla/squad", split="train")
# Here, there is no progress bar on the row parsing step
```

**Describe the solution you'd like**
After pulling the data from HF and during the record creation (from HF format to `rg.FeedbackRecord` format), a progress bar should be shown to notify users. Otherwise, it looks like the process is frozen.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by Racso-3141** [comment]
May I give it a try?

**Comment by alvarobartt** [comment]
Hi @Racso-3141 sure, you can give it a try! Only thing to take into consideration is that as of https://github.com/argilla-io/argilla/pull/3784 we detached the remote (in Argilla) schemas from the local ones, but you should be ready to do so from `develop`.

Also take into consideration that you may find some bugs, but since this feature is unreleased yet, you can report those as I'm tackling those separately at https://github.com/argilla-io/argilla/pull/3829

Thank you in advance! 🤗

**Comment by davidberenstein1957** [comment]
Hi @Racso-3141 are you still interested in processing this?

**Comment by Racso-3141** [comment]
Yes. Sorry I am a little busy after the fall break.

**Comment by Racso-3141** [comment]
Hello, @davidberenstein1957, I submitted a pull request for this issue. Thank you.
