### ISSUE TITLE
[BUG-python/deployment] `RemoteFeedbackDataset` `pull` does not convert record to local

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4052]
**Describe the bug**
We were doing a demo and saw this bug where the records are still `RemoteFeedbackRecords`.

**Stacktrace and Code to create the bug**
N.A.

**Expected behaviour**
N.A.

**Additional context**
N.A.

**Comment by alvarobartt** [comment]
Hi @davidberenstein1957 could you elaborate a bit on this? Which `argilla` version are you using? I've checked since 1.17.0 and we are calling `to_local` before returning those to the local instance, and before we were just dumping the Python dict so IMO the `RemoteFeedbackDataset` shouldn't have been returned ever on the `pull` call. Anyway, feel free to provide more context and I'll look into it, thanks!

**Comment by davidberenstein1957** [comment]
Sorry @alvarobartt , went for lunch and did not have time to fine-tune.

**Comment by alvarobartt** [comment]
No worries, feel free to ping once updated, thanks 🤗
