### ISSUE TITLE
[FEATURE] add `virtual machine` image to client deployment on IDC

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4148]
We want to be able to deploy Argilla on the Intel Developer Cloud.

**Comment by gabrielmbmb** [comment]
I already deployed Argilla on an IDC machine using both with and without docker. I asked Intel what's the "format" they expect, because not sure if they will create an snapshot of the machine, if we have to provide an startup script that install everything, ...

So for now i'm blocked until I have more details from Intel.
