### ISSUE TITLE
Add text2text example (e.g., text summarisation)

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#419]
Add the text summarisation fine-tuning tutorial similar to sentiment classifier fine-tuning tutorial:

https://rubrix.readthedocs.io/en/stable/tutorials/06-labeling-finetuning.html#3.-Fine-tune-the-pre-trained-mode

**Comment by iakhil** [comment]
I'd like to work on this, however, it seems the URL provided is outdated/broken.

**Comment by dvsrepo** [comment]
Hi @iakhil ! You are right!

I think the best for this issue is to add a text summarization example here:

https://rubrix.readthedocs.io/en/stable/guides/task_examples.html#Text2Text-(Experimental)

The idea is use text summarization pretrained pipeline from Huggingface (https://huggingface.co/transformers/main_classes/pipelines.html#summarizationpipeline) and add the example in this notebook (after the machine translation one):

https://github.com/recognai/rubrix/blob/master/docs/guides/task_examples.ipynb

For example:

```python
summarizer = pipeline("summarization")
# return three predictions
predictions = summarizer("A LONG TEXT....", num_return_sequences=3)

# log three predictions in rubrix
# follow the machine translation example
```

**Comment by dvsrepo** [comment]
Hi @iakhil , did you manage to take a look at this? Let us know if you need support

**Comment by iakhil** [comment]
Hey! I did have a look and managed to write the example. However, I am having bit of a trouble to test it at my end. I understand  `wget -O docker-compose.yml https://raw.githubusercontent.com/recognai/rubrix/master/docker-compose.yaml && docker-compose up` should be run to launch the docker-contained web app. I get the 'wget is not recognised error' on Windows which I reckon would be solved by installing Wget and adding to the path in the Environment Variables. Unfortunately, I couldn't seem to get that going — I am downloading Wget from [here](https://eternallybored.org/misc/wget/). If this is the right place to download it, please point towards any specific version. Thank you.

**Comment by iakhil** [comment]
Hey! In order to log predictions in Rubrix, the Docker-contained web app should be running, right? When I try to run it using the first method, I get the following error: 

`E:\rubrix>wget -O docker-compose.yml https://raw.githubusercontent.com/recognai/rubrix/master/docker-compose.yaml && docker-compose up
converted 'https://raw.githubusercontent.com/recognai/rubrix/master/docker-compose.yaml' (ASCII) -> 'https://raw.githubusercontent.com/recognai/rubrix/master/docker-compose.yaml' (UTF-8)
--2021-11-06 02:35:07--  https://raw.githubusercontent.com/recognai/rubrix/master/docker-compose.yaml
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
Unable to establish SSL connection.`

How should I go about it?

**Comment by frascuchon** [comment]
Hi @iakhil 

There are some troubles with SSL certificates downloading the docker-compose.yml file.

You can just copy the [file content](https://raw.githubusercontent.com/recognai/rubrix/master/docker-compose.yaml) and create it locally. Then launch the `docker-compose up` command.

I hope this helps you

**Comment by iakhil** [comment]
Thanks! I got it running. Are we supposed to have three predictions (as denote by the value of  `num_return_sequences`)? In Rubrix, I can see only one prediction for both machine translation and text summarization.

**Comment by dvsrepo** [comment]
Hi @iakhil, sorry for the late reply. In principle you should be able to view the 3 predictions using the arrows on both the annotation and explore mode. Would you mind to share a screenshot with the records for which you don't see the predictions?

**Comment by iakhil** [comment]
Earlier, I had connected to the server locally using `python -m rubrix.server` but now it doesn't seem to work. I get an error that says `ERROR:    Application startup failed. Exiting.` Any way to fix this?

**Comment by krishnajalan** [comment]
Hey! Can I pick this issue under Hacktoberfest ? if its still pending?

**Comment by dvsrepo** [comment]
Absolutely! It's still pending

**Comment by davidberenstein1957** [comment]
@krishnajalan @iakhil https://docs.argilla.io/en/latest/guides/tasks/text_generation.html#Text-Summarization
