### ISSUE TITLE
[BUG-python] `FloatMetadataProperty`: value is not a valid `float` when it is an rounded integer

### ISSUE THREAD

**Issue by sdiazlor** [recognai/rubrix#4570]
**Describe the bug**
Using `distilabel` and `to_argilla` method raises this error regarding metadata and `text-descriptives`.

```bash
ValueError: `FeedbackRecord.metadata` {'length-input': 19, 'length-instructions': 106, 'generation-model': 
'gpt-3.5-turbo', 'input_n_tokens': 2, 'input_n_unique_tokens': 2, 'input_n_sentences': 1, 'input_perplexity': 1, 
'input_entropy': 0, 'input_flesch_reading_ease': -48.99, 'instructions_n_tokens': 18, 
'instructions_n_unique_tokens': 18, 'instructions_n_sentences': 1, 'instructions_perplexity': 1.79, 
'instructions_entropy': 0.58, 'instructions_flesch_reading_ease': 61.67} does not match the expected schema, with 
exception: 2 validation errors for MetadataSchema
input_perplexity
  value is not a valid float (type=type_error.float)
input_entropy
  value is not a valid float (type=type_error.float)
```

**Expected behavior**
I would expect this check to pass given that any integer is a rounded of float.

**Environment:**
 - Argilla Version [e.g. 1.0.0]: 1.23
 - ElasticSearch Version [e.g. 7.10.2]:
 - Docker Image (optional) [e.g. argilla:v1.0.0]: 

**Additional context**

**Comment by davidberenstein1957** [comment]
@frascuchon, this might also be the case for `IntMetaDataProperties` working with `0` rounded numbers (`1.0`, `2.0`, etc.)

**Comment by frascuchon** [comment]
Thanks @sdiazlor and @davidberenstein1957. If this is a client validation error, it should be an error related to the pydantic behaviour. Maybe  @alvarobartt can take a look into it. He can tackle this better than me.

**Comment by alvarobartt** [comment]
May I ask how are the `metadata_properties` for the `text-descriptives` defined? Because it seems that the value is `float` which is a Python type that should go from `float(1) -> 1.0`, so I cannot see the issue with the provided information, could you answer the question above and provide any other information that can be useful? i.e. is the issue only within the `to_argilla` method of `distilabel` or also in `argilla` Python package?

AFAIK @davidberenstein1957 worked on that integration and I'm not really aware about the `text-descriptives` details, could you double check @davidberenstein1957? Thanks

**Comment by davidberenstein1957** [comment]
@sdiazlor worked on this integration, I checked it. I think the issue is originating in the `text-descriptives` integration but is two-fold. 
- 1. the integration, which might be swapping a `IntegerMetadataProperty` with a `FloatMetadataProperty` during the `text-descriptives` config. @sdiazlor, would you be able to take a look here?
- However, from a usability perspective there is also the issue of not allowing for passing a rounded float like `1.0` to an `IntegerMetadataProperty` and perhaps also not an integer like`1` to a `FloatMetadataProperty`. For me this feels buggy but what do you think @alvarobartt, should we allow for this?
