### ISSUE TITLE
Adding support for QA task

### ISSUE THREAD

**Issue by lalitpagaria** [recognai/rubrix#484]
Thank you for the awesome project.

Rubrix already support many NLP tasks which is great. It would be great if it support QA task as well.

As a community maintainer of [Haystack](https://github.com/deepset-ai/haystack), I see great potential of synergies between these two project. Haystack already support customer feedback collection [API](https://haystack.deepset.ai/guides/rest-api).

@tholor @Timoeller

**Comment by dvsrepo** [comment]
Hi @lalitpagaria thanks so much for bringing this up!

Haystack is an amazing and inspiring NLP project indeed!

As for supporting QA task, it's not on our roadmap for several reasons. The first and most important one is that, as far as we see, Haystack is already providing a lot of value for the full QA lifecycle, including labelling and the feedback collection. We think that labeling and monitoring for QA can largely benefit from a highly specialised tool. We believe this is not the case for other NLProc, or even CV tasks, so we want to put our focus there. We also have not much experience with QA, but have gathered a lot of experience for other NLP tasks through projects with enterprise clients.

Having said that, we'd definitely love to hear @tholor ,  @Timoeller and your thoughts, and would be very excited to try and find potential synergies with deepset and Haystack (maybe for other tasks in Haystack's NLP pipelines? or something we're missing on the QA space).

As for monitoring and evaluation, we're going to introduce a new feature soon called: Rubrix `Metrics` (inspired by projects like http://explainaboard.nlpedia.ai/ or Robustness Gym), which might be interesting for QA as well. The main idea is to compute and provide access to local and global metrics (such as label density, or label consistency for NER) to enable fine-grained and more robust model evaluation (and training data analysis).

**Comment by tholor** [comment]
Hey @dvsrepo, 
I totally agree that QA / semantic search is quite different from many other NLP tasks and particularly the labeling process can become tricky - mainly because you don't have a fixed set of categories / classes and therefore need to handle ambiguity in labels / predictions. Also the quality of created questions has a huge impact on eval / training. I would of course be interested in seeing a labeling workflow for QA in rubrix, but I would also advise to just put it on the roadmap if you can spend substantial resources on it as a good implementation might become tricky ;)  

We only have a very basic [annotation tool ](https://haystack.deepset.ai/guides/annotation) for QA so far, but actually think of doing bigger re-works early next year where we would like to incorporate our learnings. Not sure, but maybe we can identify some synergies when we start working on this :thinking: (CC @PiffPaffM)
