### ISSUE TITLE
[BUG-python/deployment-v1] `show_progress` flag does not work for influencing logging behavior

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#5111]
**Describe the bug**

Another issue mentioned by Aleph Alpha.

**Stacktrace and Code to create the bug**

**Expected behavior**

**Environment:**

 - Argilla Version [e.g. 1.0.0]:
 - ElasticSearch Version [e.g. 7.10.2]:
 - Docker Image (optional) [e.g. argilla:v1.0.0]:

**Additional context**

**Comment by NiklasKoehneckeAA** [comment]
**Describe the bug**

Creating a FeedbackDataset always logs to the info channel without the ability to turn it off. I would argue that `show_progress` should disable this logging.

**Stacktrace and Code to create the bug**
```python
import argilla as rg

dataset = rg.FeedbackDataset(fields=[rg.TextField(name="a")], questions=[rg.RatingQuestion(name="q", values=[1,2])])
dataset.push_to_argilla("myname", show_progress=False)
```
Outputs the following info logs:
```
[06/26/24 15:24:48] INFO     INFO:argilla.client.feedback.dataset.local.mixins:✓ Dataset succesfully  mixins.py:271
                             pushed to Argilla                                                                     
                    INFO     INFO:argilla.client.feedback.dataset.local.mixins:RemoteFeedbackDataset( mixins.py:272
                                id=fe937ec9-0b3d-401b-8ecc-44968d98b39d                                            
                                name=myname                                                                        
                                workspace=Workspace(id=a08b9a81-79b9-4fd9-b6da-7f389385b2d3,                       
                             name=argilla, inserted_at=2024-06-17 10:02:05.260860,                                 
                             updated_at=2024-06-17 10:02:05.260860)                                                
                                url=http://localhost:6900/dataset/fe937ec9-0b3d-401b-8ecc-44968d98b39              
                             d/annotation-mode                                                                     
                                fields=[RemoteTextField(id=UUID('06e7ee28-3148-49f5-ac6e-ca9b52662a1f              
                             '), client=None, name='a', title='A', required=True, type='text',                     
                             use_markdown=False)]                                                                  
                                questions=[RemoteRatingQuestion(id=UUID('d4f2e93c-9af7-4597-ba6f-d092              
                             988b8fde'), client=None, name='q', title='Q', description=None,                       
                             required=True, type='rating', values=[1, 2])]                                         
                                guidelines=None                                                                    
                                metadata_properties=[]                                                             
                                vectors_settings=[]                                                                
                             )    
```
**Expected behavior**
No notification or logging is shown, as all available options have been disabled

**Environment:**
python: 3.12
Argilla Version: `argilla==1.29.0`
ElasticSearch Version [e.g. 7.10.2]: `docker.elastic.co/elasticsearch/elasticsearch:8.5.3`
Docker Image (optional) [e.g. argilla:v1.0.0]: `argilla/argilla-server:v1.29.0`

**Comment by NiklasKoehneckeAA** [comment]
Related but not quite the same issue(still somehow fits into the title):
**Describe the bug**

Setting `show_progress` to false when uploading records to a `RemoteFeedbackDataset` disables the progress bar, but still prints an empty cell in Jupyter.

**Stacktrace and Code to create the bug**
```python
import argilla as rg

dataset = rg.FeedbackDataset(fields=[rg.TextField(name="field")], questions=[rg.RatingQuestion(name="question", values=[1,2])])
dataset.push_to_argilla("myname", show_progress=False)
remote_dataset = rg.FeedbackDataset.from_argilla("myname")
for _ in range(10):
    remote_dataset.add_records(rg.FeedbackRecord(fields={"field": "value"}), show_progress=False)
```
Results in something like this:
![image](https://github.com/argilla-io/argilla/assets/155443293/3daa7b7d-f54b-4fd8-a66f-d1434d85239a)


**Expected behavior**
No empty cell is printed.

**Environment:**
python: 3.12
Argilla Version: `argilla==1.29.0`
ElasticSearch Version [e.g. 7.10.2]: `docker.elastic.co/elasticsearch/elasticsearch:8.5.3`
Docker Image (optional) [e.g. argilla:v1.0.0]: `argilla/argilla-server:v1.29.0`

**Comment by davidberenstein1957** [comment]
Adding @frascuchon to potentially fix in old version and @burtenshaw to potentially review behavior in new version.

**Comment by davidberenstein1957** [comment]
@nataliaElv, seemingly a bug fix that needs to happen

**Comment by frascuchon** [comment]
The `show_progress` argument only affects the progress bar when pushing records, nothing about the creation info. About the empty cell, any ideas @alvarobartt?
