### ISSUE TITLE
Question: remove record attributes should be allowed ?

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#525]
In rubrix, after logging some records, you can change record attributes but you cannot remove them.

For example, you can change a record prediction but you cannot remote it. Should we support this kind of updates? Is this behavior a bug?

By other hand, this new behaviour could difficult partial updates, and you should send the whole data record each time

@dvsrepo @dcfidalgo

**Comment by dcfidalgo** [comment]
As discussed with @frascuchon on slack, I would prefer the behavior of replacing the records, rather than partially updating them. Until now I supposed that this was the case, so I never really had the need for partial updates of a record. 
Often my flow is loading records from Rubrix, that is most of the time I already start with something. So having to provide the full record when you want to update it, does not feel like a big penalty to me.
