### ISSUE TITLE
[FEATURE] add `__repr__` to `argilla.settings._resource.SettingsProperties`

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#5380]
**Is your feature request related to a problem? Please describe.**

These are used for error messaging but don't show the relevant information.

**Describe the solution you'd like**

I would like to see it as normal printed settings for the dataset.

**Describe alternatives you've considered**

NA.

**Additional context**

There might be other classes that need a `__repr__`.

**Comment by phershbe** [comment]
Cool project!! I would like to work on this if it is okay. I am pretty inexperienced but this should be self-explanatory. I could check for other classes too but let me start with this. 🙂

**Comment by davidberenstein1957** [comment]
Hi @phershbe, that would be very welcome. You can tak e a look here to see how you can contribute but feel free to ask for help when needed. https://docs.argilla.io/latest/community/contributor/

**Comment by davidberenstein1957** [comment]
@phershbe are you still interested in tackling this?

**Comment by phershbe** [comment]
@davidberenstein Sorry about this. Yeah I am, I spent quite a bit of time and went through the code base and checked out the `__repr__` methods for different classes. I guess that in this case it is going to want to mention the properties but I didn't feel like I knew enough to ask a question and didn't want to submit a really sloppy pull request. I unassigned myself a few minutes ago, I will study whatever is in the pull request when it gets made. Sorry again about not letting you know before.

**Comment by bikash119** [comment]
hi @davidberenstein1957 , can I take up this?

**Comment by bikash119** [comment]
Hi @davidberenstein1957 : Can you please help me with replicating the scenarios. I was able to run all the unit tests without any failure. So, if I understand correctly, I will have to add tests to check the correctness of the code change.

**Comment by bikash119** [comment]
hi @davidberenstein1957, Request you to pls confirm if the below behavior is the expected behaviour for the below unit test.
```
def test_settings_repr(self):
        settings = rg.Settings(
            fields=[
                rg.TextField(name="text", title="text"),
                rg.ImageField(name="image", title="image"),
            ],
            metadata=[
                rg.FloatMetadataProperty("source"),
            ],
            questions=[
                rg.LabelQuestion(name="label", title="text", labels=["positive", "negative"]),
                #rg.MultiLabelQuestion(name="label", title="text", labels=["positive", "negative"]),
                rg.RatingQuestion(name="rating", title="text", values=[1, 2, 3, 4, 5]),
                rg.TextQuestion(name="text", title="text"),
                rg.SpanQuestion(name="span", 
                                title="text", field="text", 
                                labels=["Apparatus", "Method", "Machine", "Manufacture", "Design"],
                                visible_labels=3),
            ],
            vectors=[rg.VectorField(name="text", dimensions=3)],
        )
        print(settings.__repr__())
        assert (
            settings.__repr__() == f"Settings(guidelines=None, allow_extra_metadata=False, "
            "distribution=OverlapTaskDistribution(min_submitted=1), "
            f"fields={settings.fields}, questions={settings.questions}, vectors={settings.vectors}, metadata={settings.metadata})"
        )
```
## Without fix
`Settings(guidelines=None, allow_extra_metadata=False, distribution=OverlapTaskDistribution(min_submitted=1), fields=<argilla.settings._resource.SettingsProperties object at 0x7fd80ff7ea00>, questions=<argilla.settings._resource.QuestionsProperties object at 0x7fd80ff7e6d0>, vectors=<argilla.settings._resource.SettingsProperties object at 0x7fd80ff7edf0>, metadata=<argilla.settings._resource.SettingsProperties object at 0x7fd80ff7ea30>)`
## With fix
`Settings(guidelines=None, allow_extra_metadata=False, distribution=OverlapTaskDistribution(min_submitted=1), fields=[TextField(name=text, title=text, description=None, type=text, required=True)
, ImageField(name=image, title=image, description=None, type=image, required=True)
], questions=[LabelQuestion(name=label, title=text, description=None, type=label_selection, required=True)
, RatingQuestion(name=rating, title=text, description=None, type=rating, required=True)
, TextQuestion(name=text, title=text, description=None, type=text, required=True)
, SpanQuestion(name=span, title=text, description=None, type=span, required=True)
], vectors=[VectorField(name=text, title=text, dimensions=3)], metadata=[FloatMetadataProperty(name=source, title=source, visible_for_annotators=True)])`

**Comment by davidberenstein1957** [comment]
That looks great!

**Comment by bikash119** [comment]
Thanks @davidberenstein1957 , raising PR now.
