### ISSUE TITLE
[rules] New metrics layout

### ISSUE THREAD

**Issue by leiyre** [recognai/rubrix#860]

**Comment by frascuchon** [comment]
As comment, The rule metrics could take some time to be computed. It would be nice include some loading status for component if metrics take too long to be computed (instead of keep the `-` for non resolved metrics.


https://user-images.githubusercontent.com/2518789/147926024-88a616a4-2bb2-4efd-a3cb-2339ae5c8766.mov



what do you think @Amelie-V ?
