### ISSUE TITLE
[Define rules] Notification toast after saving/deleting the rule

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#874]
Global mechanism to notify completed actions. Show "The rule was saved" message as a toast notification.

**Comment by dvsrepo** [comment]
I think toast management should be reviewed and tackled in other places of the app too, and should be planned as a overall task. 

Some examples with no current toast:

- Confirmation after global/multiple annotation in Annotate Mode.
- Dataset deletion in Datasets Page
- Creating a new label 

For the Define Rules view:

- I see rule deletion toast as a bit problematic/unnecessary because we are doing a full-page reload.
- For saving the rule it's a good idea, we just need to decide what to show in the button area (@Amelie-V should review this with a bit of time).

Finally, after testing this behaviour today in my opinion it's ready for this release.
