### ISSUE TITLE
Weak labeling for token classification

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#968]

**Comment by frascuchon** [comment]
Some conclusions that we can start to discuss about WS4NER

## Lite integration with skweak

As far as I know, skweak + spaCy integration is (more or less) better option  to apply weaksupervision for token classification. We should provide  a lite integration without  big abstractions.

For example:
```python

weak_labelled_dataset = apply_rules_to_dataset_in_some_way(dataset="the_dataset", rules=<the list of rules>)
docs =weak_labelled_dataset.to_spacy()
# Here, docs will contain the `.spans`  property including `labelling_functions` annotations dictionary
```

## Agnostic data model for weak labeling

Do we need an agnostic data model representing all weak labels generated by rules?

The current data model for TokenClassification does not accept annotated entities with different agents. So, it's not possible built rules results in terms of rubrix records.

## Define a set of basic rules using query text

Here the, search keyword is fundamental and a base for rules match definitions, since they will guide the built-in rules.

For example, the rule:

```python
rule = Rule(query="mark*", label="PERSON", action="exact_match")
```
will be applied on each record as follows:

1. For each keyword in record
2. yield the matched token as a PERSON

We can think about a minimal set to easily define rule actions based on keywords. Some of them could be:

```python
# span will be defined by 2 tokens before of keyword Corp (included). "The Masala Corp." should match as ORG for this rule
Rule(query="Corp",  label="ORG", action="before_token", n_tokens=2)

# Span will be defined by 2 tokens after keyword Mr. and the keyword won`t be part of span.
Rule(query="Mr.",  label="PERSON", action="after_token", n_tokens=2, include_keyword=False)
```

## For more complex rules, you can still define your own labelling function

If you want/must define more complex rules, you can always read the dataset and convert to spacy documents, then apply the normal process described in skweak documentation for that.

## Basic UI interaction

A simple way to define rules by using the UI. Rules metrics will be limited in terms of precision, but you should  explore matched records and view the rule coverage as a basic metric.


@dcfidalgo @dvsrepo comments a proposal are really welcome

**Comment by dcfidalgo** [comment]
> Do we need an agnostic data model representing all weak labels generated by rules?

In order to keep doors open to other label models, I would vote for having such an agnostic weak label object, copying the one from [wrench](https://github.com/JieyuZ2/wrench/blob/main/wrench/dataset/seqdataset.py#L33). Maybe I would switch to numpy arrays (or even better scipy sparse arrays), instead of using `List[List[List[str]]]`. Should be more efficient when computing metrics, and also more lightweight (at least when using sparse arrays).
And for the skweak support, I would provide some method/function, that takes this weak label matrix as input and returns `FunctionAnnotator`s or a `CombinedAnnotator`. something in this direction.

> We can think about a minimal set to easily define rule actions based on keywords. Some of them could be:

:+1:
